### ISSUE TITLE
Wrong positioning when embedding in a flex container

### ISSUE THREAD

**Issue by timeu** [PolymerElements/iron-fit-behavior#17]
When putting a `paper-dialog` and a `paper-dialog-scrollable' inside a body that has the classes `fullbleed`, `vertical` and `layout`, the offset will be wrong. 

Reproducable: https://jsbin.com/dizison/edit?html,output
If you remove the `layout` and `vertical` classes from the `body` tag it will work fine. 

The problem is that this line will result in a negative offset: 
https://github.com/PolymerElements/iron-fit-behavior/blob/master/iron-fit-behavior.html#L229

**Comment by cdata** [comment]
I'm sorry, but the reported issue is a little too vague to be actionable. Can you provide screenshots of the expected result and the actual result from your test case, and then re-open? Thanks!

**Comment by timeu** [comment]
It seems that the issue isn't reproducable anymore.

Soem more infos:
When I created the issue, the problem was, that the dialog was bigger than the visible screen because `var sizingOffset = this[offsetExtent] - this.sizingTarget[offsetExtent];` returned a negative value (when the body was flexed) and thus `maxHeight` was bigger than it should be.
