### ISSUE TITLE
Badly sized dialog, some strange interaction with padding-top

### ISSUE THREAD

**Issue by atotic** [PolymerElements/iron-fit-behavior#19]
See http://jsbin.com/roqube/edit?html,output

Observed:
As you size window up and down, the size of the dialog changes. Sometimes it'll display just one line, sometimes 2, sometimes 3.
Expected:
Dialog should show all 3 lines.

Started tracing throught the code, it got tricky....

![screen shot 2015-08-18 at 11 33 45 am](https://cloud.githubusercontent.com/assets/127453/9339086/04a97676-459d-11e5-8604-04d4e6cd73f9.png)

**Comment by padster** [comment]
Is it the same as this?
https://github.com/PolymerElements/iron-fit-behavior/issues/20

I fixed mine by moving the block:
      if (!this._fitInfo.positionedBy.vertically || !this._fitInfo.positionedBy.horizontally) {
        // need position:fixed to center
        this.style.position = 'fixed';
      }
up into the start of constrain()

**Comment by atotic** [comment]
No longer reproducible on master.
