### ISSUE TITLE
Wrong position on open due to incorrect measure position

### ISSUE THREAD

**Issue by padster** [PolymerElements/iron-fit-behavior#20]
I ran into an issue where the popup was measured incorrectly before being opened.

Tracking it down, the error is in these lines:
https://github.com/PolymerElements/iron-fit-behavior/blob/master/iron-fit-behavior.html#L204

Setting this.style.top / this.style.left to '0px' inside constrain() has no effect, as the position:fixed isn't added until inside center()

Is it ok just to move the position:fixed set to within constrain instead?

**Comment by cyscott** [comment]
I was having the same problem. Your suggested solution worked for me.

**Comment by cdata** [comment]
Can you provide more specific conditions under which this would occur, and then re-open the issue? Thanks!

**Comment by padster** [comment]
I can't give the exact example I triggered it with, but to summarize, it was along the lines of:
<body>
  <root-view>
    <paper-drawer-panel>... </>
    <paper-dialog modal> ...content... </>
  </>
</>

Stuff inside the panel was used to fill content in the dialog, then open it centered in the middle of the page. It would pop up incorrectly, due to measure issue mentioned in line 3 of the original post.
