### ISSUE TITLE
max-width and max-height positioning issues

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/iron-fit-behavior#29]
When setting `max-width` or `max-height` to the element, the first time positioning is properly calculated, but on the following `refit()` calls it will be positioned in the wrong place.
```html
<style>
  .sized {
    max-width: 200px;
  }
</style>

<simple-fit auto-fit-on-attach class="sized" onclick="this.refit()">
  Hello
</simple-fit>

**Comment by bendavis78** [comment]
Here's an example of where this can become an issue: http://output.jsbin.com/taxoli

View that link on a mobile phone, focus the text field to bring up the keyboard (which resizes the window), then click on the button to open the dialog. 
Here's an example of where this can become an issue: http://output.jsbin.com/taxoli

View that link on a mobile phone, focus the text field to bring up the keyboard (which resizes the window), then click on the button to open the dialog.

**Comment by bendavis78** [comment]
It looks like the main issue is in `_resetFit()`. It doesn't reset `top` or `left` if `_fitInfo.sizedBy.height` is true.  Shouldn't the lines that sets `top` and `left` be put in their own condition that checks `_fitInfo.positionedBy` instead of `_fitInfo.sizedBy`?

**Comment by motss** [comment]
How about explicitly calling `refit()` before opening it.

```
open: function () {
    this.refit();
    this.open();
}
```
