### ISSUE TITLE
fit-into-position property

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/iron-fit-behavior#36]
Currently `iron-fit-behavior` centers the element into `fitInto`.
It would be useful to have a property `fit-into-position` to set where the element should be positioned.
This would be useful for elements like `paper-toast` (e.g. see https://github.com/PolymerElements/paper-toast/issues/67) or `iron-dropdown`

It would be a string with 1 or two parts:  `vertical horizontal`, `vertical` or `horizontal`, with `vertical = top | middle | bottom` and `horizontal = left | center | right`.
e.g.
```html
<paper-toast fit-into-position="bottom left"></paper-toast>
<iron-dropdown fit-into-position="bottom right"></iron-dropdown>
```

The default value of `fit-into-position` should be `middle center`.

@cdata @notwaldorf FYI, please let me know if you have a better name for this kind of property :)

**Comment by valdrinkoshi** [comment]
Maybe is better having 2 properties `vertical-fit` and `horizontal-fit`. WDYT?

**Comment by jarrodek** [comment]
I'm currently fighting with this issue.

I use `paper-material` as a container and `paper-item`s to display `autocomplete` propositions list below `iron-input` field. It works well if I can set up position of the `autocomplete` element via CSS. However, if I create a dynamic list of inputs (in `dom-repeat`) that use the same `autocomplete` element then it's not working well.

I want to use only one `autocomplete` element to not create additional DOM elements if it is not necessary. My element changes the `target` property (which is the input element) to listen for value changes. In the same listener I must to perform some calculations to position the element relatively to the input. So I started wondering that it would be nice to have some property to set in the behavior that will fit element into one element (window in this case) and position it to another (input field in my example). This could extend your proposition (@valdrinkoshi) of having two properties that will tell how to position the element but relatively to another element (could be `this` by default).

Example use case:
```xml
<template is="dom-repeat" id="list" items="{{list}}">
  <div class="form-row">
    <input is="iron-input" on-focus="inputFocus" type="text" value="{{item.name::input}}"/>
  </div>
</template>
<positioned-element vertical-fit="left" horizontal-fit="bottom" positionTarget="[[positionTarget]]"></positioned-element>
```
```javascript
...
inputFocus: function(e) {
  this.set('positionTarget', e.target);
}
...
```
In example above the `positioned-element` should be positioned relatively to `positionTarget` to the bottom and left.
