### ISSUE TITLE
horizontalAlign = center, verticalAlign = middle

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/iron-fit-behavior#43]
Feature request: "center" should be another valid value for `horizontalAlign`, likewise "middle" for `verticalAlign`

**Comment by AliMD** [comment]
Any plan to add this feature to current milestone ?

**Comment by valdrinkoshi** [comment]
Implementation available in #78 (branch `issue-43-center-middle`), if anyone is interested in testing this while it's being reviewed 👌
