### ISSUE TITLE
Animation, Dom-repeat run, tap handler all cause refit without acknowledging preset target default target 

### ISSUE THREAD

**Issue by jfrazzano** [PolymerElements/iron-fit-behavior#51]
### Description

Tap of paper burton causes top 0 left 0 refit on refit behavior when refit on wrapper element dynamic targeting (like in demo). 

Same occurred when animation (paper button ink, collapse) used on element with behavior. 

### Expected outcome

Expected the animation catch from window on refit a necessity of Dom bind and not an impel issue that negates use of animation in demo example implementation. 

### Live Demo

Have created a grid of 256 targets. Implemented the demo on element with collapse to hide reveal buttons, and with a content tag like demo.  

Using a drag dynamic refit on grid fit element able to target and "fit" to any of 256 grid squares. 

Hit the collapse however and refit sent demo fit implement to screen 00.  I tried a default target. Rewrote the behavior minor my to offer target array on failed target refit. 

Best I could manage was subdividing grid, absolute positioning the behavior and defaulting fit into so on Lisa of target on animation, wrapped element tap handler, Dom-repeat rerun or paper button push the element wouldn't jump behind drawer and remained constrained in sub section

### Steps to reproduce

Run demo just add paper buttons and collapse around buttons. Open/close collapse.  Press button. Place complex element in demo content tag. Rerun Dom-repeat. 

I just want to know if it's a known issue and if I should use other methods to grid drag and drop/fit into dashboard subsections. 

Thanks. 

I was just hoping after seeing demo it would offer a cool shortcut. 

### Browsers Affected

- [ ] Chrome 
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by valdrinkoshi** [comment]
Hi @jfrazzano, it seems you're calling `fit` instead of `refit`. 
`refit` is a shortcut for `resetFit` and `fit`. Since you're changing `positionTarget`, you'll need to reset the old fit settings before calling `fit` (`refit` does that) http://jsbin.com/zimelu/1/edit?html,output

**Comment by valdrinkoshi** [comment]
Closing this for now as is pending a response from the creator since 3 days.
Will reopen if necessary
