### ISSUE TITLE
`horizontalOffset` and `verticalOffset` usefulness

### ISSUE THREAD

**Issue by WoodyWoodsta** [PolymerElements/iron-fit-behavior#55]
### Question
I'm indirectly using `iron-fit-behavior` through `iron-overlay-behavior` to position a custom written dialog underneath another element. I'm using the `verticalOffset` attribute to create an offset between the top of the element that the dialog is aligning to and the dialog element itself, which achieves this by imperatively setting margins (top and bottom) on the dialog element. I'm wondering how useful the offset attributes are, then, when one can set margins on the dialog element via vanilla css?

It would, perhaps, be better if the offset attributes achieved the offset through the calculation of `top` and `left` properties, since these are not externally changeable. Is there any reason for this not being the case?

I can create a demo if the above is not clear! :+1:

**Comment by bicknellr** [comment]
I'm not really sure what the request is here beyond changing the internals to make these properties seem less redundant. (They're marked with `@deprecated` but our doc generator doesn't seem to pick this up! Sorry!) Is there a non-breaking change that you're proposing to `verticalOffset` and `horizontalOffset` that would let you do something more than margin in CSS? If not, I think it might be better to just update the documentation.
