### ISSUE TITLE
Sizing does not account for scrollbars

### ISSUE THREAD

**Issue by joshuahiggins** [PolymerElements/iron-fit-behavior#81]
### Description
When `iron-fit-behavior` determines `maxWidth` and `maxHeight` it does not accommodate scrollbar sizing on overflowing content.

### Expected outcome
When there is an overflow, `maxWidth` and/or `maxHeight` should be increased to accommodate the scrollbar size.

### Actual outcome
`maxWidth` and `maxHeight` are determined based on exact content size. When a scrollbar is needed, the content size is now reduced and results in wrapped text or incorrect margins.

### Live Demo
https://jsbin.com/reruwuhoci/edit?output

### Steps to reproduce
See live demo, and view difference between the 2 dropdown menus.

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Safari 11
- Presumably all browsers...

**Comment by SomethingNew71** [comment]
Oh man thanks, @joshuahiggins this will be super helpful if your fix gets merged.
