### ISSUE TITLE
postionTarget + center + middle centers on body

### ISSUE THREAD

**Issue by moodyjmz** [PolymerElements/iron-fit-behavior#89]
### Description

Target + center + middle does not work as expected

### Expected outcome

I expected it to center vertically and horizontally onto the target

### Actual outcome

It centers onto the body

### Live Demo

https://www.webcomponents.org/element/PolymerElements/iron-fit-behavior/demo/demo/index.html

### Steps to reproduce

- Choose a target
- Select center + middle

### Browsers Affected
- [x] Chrome
- [x] Safari 11
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

Not tested other browsers, but expect same outcome

**Comment by gregorymachon** [comment]
+1
